/**
 * Do not edit directly
 * Generated on Thu, 27 Oct 2022 21:19:52 GMT
 */

export const MdSysColorSurfaceTintLight = "#6750a4"; // Surface tint
export const MdSysColorOnErrorContainerLight = "#410e0b"; // On error container
export const MdSysColorOnErrorLight = "#ffffff"; // On error
export const MdSysColorErrorContainerLight = "#f9dedc"; // Error container
export const MdSysColorOnTertiaryContainerLight = "#31111d"; // On tertiary container
export const MdSysColorOnTertiaryLight = "#ffffff"; // On tertiary
export const MdSysColorTertiaryContainerLight = "#ffd8e4"; // Tertiary container
export const MdSysColorTertiaryLight = "#7d5260"; // Tertiary
export const MdSysColorShadowLight = "#000000"; // Shadow
export const MdSysColorErrorLight = "#b3261e"; // Error
export const MdSysColorOutlineLight = "#79747e"; // Outline
export const MdSysColorOnBackgroundLight = "#1c1b1f"; // On background
export const MdSysColorBackgroundLight = "#fffbfe"; // Background
export const MdSysColorInverseOnSurfaceLight = "#f4eff4"; // Inverse on surface
export const MdSysColorInverseSurfaceLight = "#313033"; // Inverse surface
export const MdSysColorOnSurfaceVariantLight = "#49454f"; // On surface variant
export const MdSysColorOnSurfaceLight = "#1c1b1f"; // On surface
export const MdSysColorSurfaceVariantLight = "#e7e0ec"; // Surface Variant
export const MdSysColorSurfaceLight = "#fffbfe"; // Surface
export const MdSysColorOnSecondaryContainerLight = "#1d192b"; // On secondary container
export const MdSysColorOnSecondaryLight = "#ffffff"; // On secondary
export const MdSysColorSecondaryContainerLight = "#e8def8"; // Secondary container
export const MdSysColorSecondaryLight = "#625b71"; // Secondary
export const MdSysColorInversePrimaryLight = "#d0bcff"; // Inverse primary
export const MdSysColorOnPrimaryContainerLight = "#21005d"; // On primary container
export const MdSysColorOnPrimaryLight = "#ffffff"; // On primary
export const MdSysColorPrimaryContainerLight = "#eaddff"; // Primary container
export const MdSysColorPrimaryLight = "#6750a4"; // Primary
export const MdSysColorSurfaceTintDark = "#6750a4"; // Surface tint
export const MdSysColorOnErrorContainerDark = "#f2b8b5"; // On error container
export const MdSysColorOnErrorDark = "#601410"; // On error
export const MdSysColorErrorContainerDark = "#8c1d18"; // Error container
export const MdSysColorOnTertiaryContainerDark = "#ffd8e4"; // On tertiary container
export const MdSysColorOnTertiaryDark = "#492532"; // On tertiary
export const MdSysColorTertiaryContainerDark = "#633b48"; // Tertiary container
export const MdSysColorTertiaryDark = "#efb8c8"; // Tertiary
export const MdSysColorShadowDark = "#000000"; // Shadow
export const MdSysColorErrorDark = "#f2b8b5"; // Error
export const MdSysColorOutlineDark = "#938f99"; // Outline
export const MdSysColorOnBackgroundDark = "#e6e1e5"; // On background
export const MdSysColorBackgroundDark = "#1c1b1f"; // Background
export const MdSysColorInverseOnSurfaceDark = "#313033"; // Inverse on surface
export const MdSysColorInverseSurfaceDark = "#e6e1e5"; // Inverse surface
export const MdSysColorOnSurfaceVariantDark = "#cac4d0"; // On surface variant
export const MdSysColorOnSurfaceDark = "#e6e1e5"; // On surface
export const MdSysColorSurfaceVariantDark = "#49454f"; // Surface Variant
export const MdSysColorSurfaceDark = "#1c1b1f"; // Surface
export const MdSysColorOnSecondaryContainerDark = "#e8def8"; // On secondary container
export const MdSysColorOnSecondaryDark = "#332d41"; // On secondary
export const MdSysColorSecondaryContainerDark = "#4a4458"; // Secondary container
export const MdSysColorSecondaryDark = "#ccc2dc"; // Secondary
export const MdSysColorInversePrimaryDark = "#6750a4"; // Inverse primary
export const MdSysColorOnPrimaryContainerDark = "#eaddff"; // On primary container
export const MdSysColorOnPrimaryDark = "#381e72"; // On primary
export const MdSysColorPrimaryContainerDark = "#4f378b"; // Primary container
export const MdSysColorPrimaryDark = "#d0bcff"; // Primary
export const MdSysColorSurfaceTint = "#6750a4"; // Surface tint
export const MdSysColorOnErrorContainer = "#410e0b"; // On error container
export const MdSysColorOnError = "#ffffff"; // On error
export const MdSysColorErrorContainer = "#f9dedc"; // Error container
export const MdSysColorOnTertiaryContainer = "#31111d"; // On tertiary container
export const MdSysColorOnTertiary = "#ffffff"; // On tertiary
export const MdSysColorTertiaryContainer = "#ffd8e4"; // Tertiary container
export const MdSysColorTertiary = "#7d5260"; // Tertiary
export const MdSysColorShadow = "#000000"; // Shadow
export const MdSysColorError = "#b3261e"; // Error
export const MdSysColorOutline = "#79747e"; // Outline
export const MdSysColorOnBackground = "#1c1b1f"; // On background
export const MdSysColorBackground = "#fffbfe"; // Background
export const MdSysColorInverseOnSurface = "#f4eff4"; // Inverse on surface
export const MdSysColorInverseSurface = "#313033"; // Inverse surface
export const MdSysColorOnSurfaceVariant = "#49454f"; // On surface variant
export const MdSysColorOnSurface = "#1c1b1f"; // On surface
export const MdSysColorSurfaceVariant = "#e7e0ec"; // Surface Variant
export const MdSysColorSurface = "#fffbfe"; // Surface
export const MdSysColorOnSecondaryContainer = "#1d192b"; // On secondary container
export const MdSysColorOnSecondary = "#ffffff"; // On secondary
export const MdSysColorSecondaryContainer = "#e8def8"; // Secondary container
export const MdSysColorSecondary = "#625b71"; // Secondary
export const MdSysColorInversePrimary = "#d0bcff"; // Inverse primary
export const MdSysColorOnPrimaryContainer = "#21005d"; // On primary container
export const MdSysColorOnPrimary = "#ffffff"; // On primary
export const MdSysColorPrimaryContainer = "#eaddff"; // Primary container
export const MdSysColorPrimary = "#6750a4"; // Primary
export const MdRefPaletteError0 = "#000000"; // Error 0
export const MdRefPaletteError10 = "#410e0b"; // Error 10
export const MdRefPaletteError20 = "#601410"; // Error 20
export const MdRefPaletteError30 = "#8c1d18"; // Error 30
export const MdRefPaletteError40 = "#b3261e"; // Error 40
export const MdRefPaletteError50 = "#dc362e"; // Error 50
export const MdRefPaletteError60 = "#e46962"; // Error 60
export const MdRefPaletteError70 = "#ec928e"; // Error 70
export const MdRefPaletteError80 = "#f2b8b5"; // Error 80
export const MdRefPaletteError90 = "#f9dedc"; // Error 90
export const MdRefPaletteError95 = "#fceeee"; // Error 95
export const MdRefPaletteError99 = "#fffbf9"; // Error 99
export const MdRefPaletteError100 = "#ffffff"; // Error 100
export const MdRefPaletteTertiary0 = "#000000"; // Tertiary 0
export const MdRefPaletteTertiary10 = "#31111d"; // Tertiary 10
export const MdRefPaletteTertiary20 = "#492532"; // Tertiary 20
export const MdRefPaletteTertiary30 = "#633b48"; // Tertiary 30
export const MdRefPaletteTertiary40 = "#7d5260"; // Tertiary 40
export const MdRefPaletteTertiary50 = "#986977"; // Tertiary 50
export const MdRefPaletteTertiary60 = "#b58392"; // Tertiary 60
export const MdRefPaletteTertiary70 = "#d29dac"; // Tertiary 70
export const MdRefPaletteTertiary80 = "#efb8c8"; // Tertiary 80
export const MdRefPaletteTertiary90 = "#ffd8e4"; // Tertiary 90
export const MdRefPaletteTertiary95 = "#ffecf1"; // Tertiary 95
export const MdRefPaletteTertiary99 = "#fffbfa"; // Tertiary 99
export const MdRefPaletteTertiary100 = "#ffffff"; // Tertiary 100
export const MdRefPaletteSecondary0 = "#000000"; // Secondary 0
export const MdRefPaletteSecondary10 = "#1d192b"; // Secondary 10
export const MdRefPaletteSecondary20 = "#332d41"; // Secondary 20
export const MdRefPaletteSecondary30 = "#4a4458"; // Secondary 30
export const MdRefPaletteSecondary40 = "#625b71"; // Secondary 40
export const MdRefPaletteSecondary50 = "#7a7289"; // Secondary 50
export const MdRefPaletteSecondary60 = "#958da5"; // Secondary 60
export const MdRefPaletteSecondary70 = "#b0a7c0"; // Secondary 70
export const MdRefPaletteSecondary80 = "#ccc2dc"; // Secondary 80
export const MdRefPaletteSecondary90 = "#e8def8"; // Secondary 90
export const MdRefPaletteSecondary95 = "#f6edff"; // Secondary 95
export const MdRefPaletteSecondary99 = "#fffbfe"; // Secondary 99
export const MdRefPaletteSecondary100 = "#ffffff"; // Secondary 100
export const MdRefPalettePrimary0 = "#000000"; // Primary 0
export const MdRefPalettePrimary10 = "#21005d"; // Primary 10
export const MdRefPalettePrimary20 = "#381e72"; // Primary 20
export const MdRefPalettePrimary30 = "#4f378b"; // Primary 30
export const MdRefPalettePrimary40 = "#6750a4"; // Primary 40
export const MdRefPalettePrimary50 = "#7f67be"; // Primary 50
export const MdRefPalettePrimary60 = "#9a82db"; // Primary 60
export const MdRefPalettePrimary70 = "#b69df8"; // Primary 70
export const MdRefPalettePrimary80 = "#d0bcff"; // Primary 80
export const MdRefPalettePrimary90 = "#eaddff"; // Primary 90
export const MdRefPalettePrimary95 = "#f6edff"; // Primary 95
export const MdRefPalettePrimary99 = "#fffbfe"; // Primary 99
export const MdRefPalettePrimary100 = "#ffffff"; // Primary 100
export const MdRefPaletteNeutralVariant0 = "#000000"; // Neutral Variant 0
export const MdRefPaletteNeutralVariant10 = "#1d1a22"; // Neutral Variant 10
export const MdRefPaletteNeutralVariant20 = "#322f37"; // Neutral Variant 20
export const MdRefPaletteNeutralVariant30 = "#49454f"; // Neutral Variant 30
export const MdRefPaletteNeutralVariant40 = "#605d66"; // Neutral Variant 40
export const MdRefPaletteNeutralVariant50 = "#79747e"; // Neutral Variant 50
export const MdRefPaletteNeutralVariant60 = "#938f99"; // Neutral Variant 60
export const MdRefPaletteNeutralVariant70 = "#aea9b4"; // Neutral Variant 70
export const MdRefPaletteNeutralVariant80 = "#cac4d0"; // Neutral Variant 80
export const MdRefPaletteNeutralVariant90 = "#e7e0ec"; // Neutral Variant 90
export const MdRefPaletteNeutralVariant95 = "#f5eefa"; // Neutral Variant 95
export const MdRefPaletteNeutralVariant99 = "#fffbfe"; // Neutral Variant 99
export const MdRefPaletteNeutralVariant100 = "#ffffff"; // Neutral Variant 100
export const MdRefPaletteNeutral0 = "#000000"; // Neutral 0
export const MdRefPaletteNeutral10 = "#1c1b1f"; // Neutral 10
export const MdRefPaletteNeutral20 = "#313033"; // Neutral 20
export const MdRefPaletteNeutral30 = "#484649"; // Neutral 30
export const MdRefPaletteNeutral40 = "#605d62"; // Neutral 40
export const MdRefPaletteNeutral50 = "#787579"; // Neutral 50
export const MdRefPaletteNeutral60 = "#939094"; // Neutral 60
export const MdRefPaletteNeutral70 = "#aeaaae"; // Neutral 70
export const MdRefPaletteNeutral80 = "#c9c5ca"; // Neutral 80
export const MdRefPaletteNeutral90 = "#e6e1e5"; // Neutral 90
export const MdRefPaletteNeutral95 = "#f4eff4"; // Neutral 95
export const MdRefPaletteNeutral99 = "#fffbfe"; // Neutral 99
export const MdRefPaletteNeutral100 = "#ffffff"; // Neutral 100
export const MdRefPaletteBlack = "#000000"; // Black
export const MdRefPaletteWhite = "#ffffff"; // White
export const MdSysTypescaleLabelSmallFamily = "Roboto";
export const MdSysTypescaleLabelSmallWeight = "500";
export const MdSysTypescaleLabelMediumFamily = "Roboto";
export const MdSysTypescaleLabelMediumWeight = "500";
export const MdSysTypescaleLabelLargeFamily = "Roboto";
export const MdSysTypescaleLabelLargeWeight = "500";
export const MdSysTypescaleBodySmallFamily = "Roboto";
export const MdSysTypescaleBodySmallWeight = "400";
export const MdSysTypescaleBodyMediumFamily = "Roboto";
export const MdSysTypescaleBodyMediumWeight = "400";
export const MdSysTypescaleBodyLargeFamily = "Roboto";
export const MdSysTypescaleBodyLargeWeight = "400";
export const MdSysTypescaleTitleSmallFamily = "Roboto";
export const MdSysTypescaleTitleSmallWeight = "500";
export const MdSysTypescaleTitleMediumFamily = "Roboto";
export const MdSysTypescaleTitleMediumWeight = "500";
export const MdSysTypescaleTitleLargeFamily = "Roboto";
export const MdSysTypescaleTitleLargeWeight = "400";
export const MdSysTypescaleHeadlineSmallFamily = "Roboto";
export const MdSysTypescaleHeadlineSmallWeight = "400";
export const MdSysTypescaleHeadlineMediumFamily = "Roboto";
export const MdSysTypescaleHeadlineMediumWeight = "400";
export const MdSysTypescaleHeadlineLargeFamily = "Roboto";
export const MdSysTypescaleHeadlineLargeWeight = "400";
export const MdSysTypescaleDisplaySmallFamily = "Roboto";
export const MdSysTypescaleDisplaySmallWeight = "400";
export const MdSysTypescaleDisplayMediumFamily = "Roboto";
export const MdSysTypescaleDisplayMediumWeight = "400";
export const MdSysTypescaleDisplayLargeFamily = "Roboto";
export const MdSysTypescaleDisplayLargeWeight = "400";
export const MdSysTypescaleLabelSmallSize = "11rem";
export const MdSysTypescaleLabelMediumSize = "12rem";
export const MdSysTypescaleLabelLargeSize = "14rem";
export const MdSysTypescaleBodySmallSize = "12rem";
export const MdSysTypescaleBodyMediumSize = "14rem";
export const MdSysTypescaleBodyLargeSize = "16rem";
export const MdSysTypescaleTitleSmallSize = "14rem";
export const MdSysTypescaleTitleMediumSize = "16rem";
export const MdSysTypescaleTitleLargeSize = "22rem";
export const MdSysTypescaleHeadlineSmallSize = "24rem";
export const MdSysTypescaleHeadlineMediumSize = "28rem";
export const MdSysTypescaleHeadlineLargeSize = "32rem";
export const MdSysTypescaleDisplaySmallSize = "36rem";
export const MdSysTypescaleDisplayMediumSize = "45rem";
export const MdSysTypescaleDisplayLargeSize = "57rem";
export const MdRefTypefacePlain = "Roboto"; // Plain typeface
export const MdRefTypefaceBrand = "Roboto"; // Brand typeface
export const MdRefTypefaceWeightBold = "700"; // Bold weight
export const MdRefTypefaceWeightMedium = "500"; // Medium weight
export const MdRefTypefaceWeightRegular = "400"; // Regular weight
export const MdSysTypescaleLabelSmallTracking = "0.5";
export const MdSysTypescaleLabelSmallLineHeight = "16"; // typescale label small line height
export const MdSysTypescaleLabelMediumLineHeight = "16"; // Typescale label medium line height
export const MdSysTypescaleLabelMediumTracking = "0.5"; // typescale label medium tracking
export const MdSysTypescaleLabelLargeLineHeight = "20"; // Typescale label large line height
export const MdSysTypescaleLabelLargeTracking = "0.1"; // Typescale label large tracking
export const MdSysTypescaleBodySmallTracking = "0.4"; // Typescale body small tracking
export const MdSysTypescaleBodySmallLineHeight = "16"; // typescale body small line-height
export const MdSysTypescaleBodyMediumLineHeight = "20"; // typescale body medium line-height
export const MdSysTypescaleBodyMediumTracking = "0.25"; // typescale body medium.tracking
export const MdSysTypescaleBodyLargeLineHeight = "24"; // typescale body large line-height
export const MdSysTypescaleBodyLargeTracking = "0.5"; // typescale body large tracking
export const MdSysTypescaleTitleSmallLineHeight = "20"; // typescale title small line-height
export const MdSysTypescaleTitleSmallTracking = "0.1"; // typescale title small tracking
export const MdSysTypescaleTitleMediumLineHeight = "24"; // typescale title medium line-height
export const MdSysTypescaleTitleMediumTracking = "0.15"; // typescale title medium.tracking
export const MdSysTypescaleTitleLargeLineHeight = "28"; // typescale title large line-height
export const MdSysTypescaleTitleLargeTracking = "0"; // title large tracking
export const MdSysTypescaleHeadlineSmallLineHeight = "32"; //  typescale headline small line height
export const MdSysTypescaleHeadlineSmallTracking = "0"; // typescale headline  small.tracking
export const MdSysTypescaleHeadlineMediumLineHeight = "36"; // typescale headline medium line-height
export const MdSysTypescaleHeadlineMediumTracking = "0"; // typescale headline medium tracking
export const MdSysTypescaleHeadlineLargeLineHeight = "40"; // typescale headline large line height
export const MdSysTypescaleHeadlineLargeTracking = "0"; // typescale headline large tracking
export const MdSysTypescaleDisplaySmallLineHeight = "44"; // typescale display small line-height
export const MdSysTypescaleDisplaySmallTracking = "0"; // typescale display-small tracking
export const MdSysTypescaleDisplayMediumLineHeight = "52"; // typescale display medium line height
export const MdSysTypescaleDisplayMediumTracking = "0";
export const MdSysTypescaleDisplayLargeLineHeight = "64"; // typescale display large line-height
export const MdSysTypescaleDisplayLargeTracking = "0"; // typescale display large tracking

export const MdSysSpacingXxxSmall = "4"; // spacing xxx small
export const MdSysSpacingXxSmall = "8"; // spacing xx small
export const MdSysSpacingXSmall = "12"; // spacing x small
export const MdSysSpacingSmall = "16"; // spacing small
export const MdSysSpacingMedium = "24"; // spacing medium
export const MdSysSpacingLarge = "32"; // spacing large
export const MdSysSpacingXLarge = "48"; // spacing x large
export const MdSysSpacingXxLarge = "56"; // spacing xx large
export const MdSysSpacingXxxLarge = "64"; // spacing xxx large
